name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: 
      - self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run:
          xcodebuild build-for-testing -scheme Test -project Test.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0'
      - name: Test
        run:
          xcodebuild test-without-building -scheme Test -project Test.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0'