name: simple

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: run a one-line script
        run: 
          echo Hello, world!
          sleep 15
          echo Goodbye!
      - name: Run a multi-line script
        run:
          echo "${{ github.workspace }}"
      - name: Run tests
        run: xcodebuild test -scheme Test -project Test.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5'

